DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE COURSE;
DROP TABLE STUDENT;
DROP TABLE PROFESSOR;

CREATE TABLE STUDENT(
    STUDENT_NO   NUMBER,
    STUDENT_NAME VARCHAR2(15 BYTE),
    ADDRESS      VARCHAR2(30 BYTE),
    GRADE        NUMBER,
    PROFESSOR_NO NUMBER
);

CREATE TABLE PROFESSOR(
    PROFESSOR_NO      NUMBER,
    PROFESSOR_NAME    VARCHAR2(15 BYTE),
    PROFESSOR_SUBJECT VARCHAR2(30 BYTE)
);

CREATE TABLE LECTURE(
    LECTURE_NO   NUMBER,
    PROFESSOR_NO NUMBER,
    ENROLL_NO    NUMBER,
    LECTURE_NAME VARCHAR2(30 BYTE),
    LECTUREROOM  VARCHAR2(15 BYTE)
);

CREATE TABLE ENROLL(
    ENROLL_NO   NUMBER,
    STUDENT_NO  NUMBER,
    COURSE_NO   NUMBER,
    ENROLL_DATE DATE
);

CREATE TABLE COURSE(
    COURSE_NO   NUMBER,
    COURSE_NAME VARCHAR2(30 BYTE),
    CREDITS     NUMBER
);

-- 기본키
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_NO);
ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY(PROFESSOR_NO);
ALTER TABLE LECTURE ADD CONSTRAINT LECTURE_PK PRIMARY KEY(LECTURE_NO);
ALTER TABLE ENROLL ADD CONSTRAINT ENROLL_PK PRIMARY KEY(ENROLL_NO);
ALTER TABLE COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY(COURSE_NO);

--외래키
ALTER TABLE STUDENT
    ADD CONSTRAINT STUDENT_PROFESSOR_FK FOREIGN KEY(PROFESSOR_NO)
    REFERENCES PROFESSOR(PROFESSOR_NO);
    
ALTER TABLE LECTURE
    ADD CONSTRAINT LECTURE_PROFESSOR_FK FOREIGN KEY(PROFESSOR_NO)
    REFERENCES PROFESSOR(PROFESSOR_NO);
    
ALTER TABLE LECTURE
    ADD CONSTRAINT LECTURE_ENROLL_FK FOREIGN KEY(ENROLL_NO)
    REFERENCES ENROLL(ENROLL_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY(STUDENT_NO)
    REFERENCES STUDENT(STUDENT_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT ENROLL_COURSE_FK FOREIGN KEY(COURSE_NO)
    REFERENCES COURSE(COURSE_NO);
    
INSERT INTO PROFESSOR VALUES(1, '이상순', '생산');
INSERT INTO PROFESSOR VALUES(2, '강기호', '디지털');
INSERT INTO PROFESSOR VALUES(3, '박장서', '디지털');



INSERT INTO STUDENT VALUES(2012140100, '이상호', '경기도', 4, 2);
INSERT INTO STUDENT VALUES(2012140112, '이창희', '대전', 4, 2);
INSERT INTO STUDENT VALUES(2012140019, '김용국', '천안', 3, 1);



INSERT INTO COURSE VALUES(




INSERT INTO ENROLL VALUES

INSERT INTO LECTURE VALUES


COMMIT;











