DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100 BYTE),
	TITLE VARCHAR2(1000 BYTE) NOT NULL,
	CONTENT VARCHAR2(4000 BYTE),
	IP VARCHAR2(20 BYTE),
	HIT NUMBER,
	CREATED DATE,
	LASTMODIFIED DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ;